### ISSUE TITLE
Cant start new second sector (PC)

### ISSUE THREAD

**Issue by AaRCaT** [RouterXdd/Icicle-World#3]
Missing Copper and Lead

![image](https://github.com/RouterXdd/Icicle-World/assets/27895684/eec9207e-89ff-4bdc-98ae-a66166542bfb)

**Comment by 000x91** [comment]
It's insisting on sending you with the default Serpulo core. I'm guessing it's something newly inherited as far as default core / default loadout

I'm seeing the same problem on Android by the way.

**Comment by Alekseiemts** [comment]
Я не могу высадится на второй сектор т. к. чтобы высадится мне нужно медь свинец и не предлагается вообще никакое ядро ну т. е. там где должно показываться с каким ядром я высаживаюсь то там просто ничего я играю с телефона

**Comment by 000x91** [comment]
Looks good with today's update.

**Comment by RouterXdd** [comment]
I am really hope the v0.8 will fix defaultLoadout problem
